// <auto-generated />
namespace MaintainMe.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updateForFullName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateForFullName));
        
        string IMigrationMetadata.Id
        {
            get { return "201812071653194_updateForFullName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
