// <auto-generated />
namespace MaintainMe.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddOwnerIdToMaintenanceAndWorkOrderTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOwnerIdToMaintenanceAndWorkOrderTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201812041753193_AddOwnerIdToMaintenanceAndWorkOrderTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
